import { PaymentStatus, PreparationStatus, DeliveryStatus } from './order-status.model';
import { User } from './user.model';
import { OrderItem } from './order-item.model';

export interface Order {
  id?: number;
  table: string;
  paymentStatus: PaymentStatus;
  preparationStatus: PreparationStatus;
  deliveryStatus: DeliveryStatus;
  creationDate?: string;  // Generated by backend
  paidAt?: string;
  preparedAt?: string;
  deliveredAt?: string;
  takenBy: User;
  orderItems: OrderItem[];
}
